### ISSUE TITLE
Authentication/Authorization enabled for metadata upload.

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#104]
AC: Discuss and agree on authentication/authorization available for metadata uploading between client and onestop api/metadata.

Select and implement:
BasicAuth using shield
Token Server
Gmail Oauth with 2-factor

**Comment by bobalink** [comment]
Metadata loading will be secured by IP filtering for the time being meaning that this story has been made irrelevant. moving to closed.

**Comment by dneufeldcu** [comment]
BasicAuth implemented via Apache in Asheville.
