### ISSUE TITLE
Complete web application separation by endpoint.

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#105]
AC: The existing code base and functionality works with search search, metadata, and admin webapps.  New artifacts are deployed to CU server.

**Comment by ajakz** [comment]
Same as work done in #47? 
Please read comments [here](https://github.com/cires-ncei/onestop/issues/47#issuecomment-288776613) and [here](https://github.com/cires-ncei/onestop/issues/83#issue-221388878)

**Comment by dneufeldcu** [comment]
This is a duplicate see above.
