### ISSUE TITLE
Add collection count to web page.

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#108]
Service endpoint provides count of collection/granule.  UI prevents * search.

- [x] UI: Disable searches that are * only from the component
- [x] UI: Display counts on landing page
- [x] ~UI: Validate THEN search (fixes a multitude of bugs)~ (New issue #111)
- [x] ~API: Figure out how to get accurate granule count~ (deferred)
- [x] API: Create total counts return via collections endpoint

**Comment by ajakz** [comment]
- [ ] UI: Disable searches that are * only from the component (no requests sent to API)
- [ ] API: Figure out how to get accurate granule count
- [ ] API: Create total counts (return collections & granules) endpoint

**Comment by ajakz** [comment]
Making a note here: I'm finding out that the only way to retrieve an accurate granules count is with the use of scripting, which we've obviously disabled. Seems like scripting functionality is more robust and secure in ES 5.x; we might be able to run a stored script in 2.x for the time being, though.

**Comment by ajakz** [comment]
In looking for where an empty search is disabled, I've spotted a bug: If a search has already been executed, when one clears out the search params and triggers a new search, collections results & selected facets are cleared but no new search is executed (so there are no results, there are no longer any selected facets, but there's a random list of facets still there). I'll work on fixing that as part of this story...
