### ISSUE TITLE
Docker Spike!

### ISSUE THREAD

**Issue by bobalink** [cires-ncei/onestop#113]
AC: Learn a part of docker.

**Comment by aaronjcaldwell** [comment]
A few thoughts about Docker as relates to OneStop Development: 

1. There's actually a gradle plugin we may want to consider that could spin up our entire system as individual containers that talk to each other. It would be useful locally but could also be pretty great as we flesh out system testing. 
2. Speaking of spinning up systems, Docker Compose is dead simple to use and another good way to spin up a system (I believe other CIRES teams are using a hybrid of 1 & 2 with their systems)
3. As we get more into this, we're going to want a place to push/store images. We could run a free instance of artifactory on one of our CU servers and use it as a Docker registry as well as a maven repository. Even better, we can use a Docker image of Artifactory, containers all the way down... We'll have to figure out authentication for Artifactory though. It's worth mentioning, Gitlab can also be used as a registry.
