### ISSUE TITLE
Performing a spatial filter across the international dateline results in an error message

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#12]
Draw a bounding box across the Pacific (intersecting the international dateline) click the search button, error message results in browser.

**Comment by mcquinne** [comment]
I'm pretty sure the simple version of this should be covered by #08692f8, but if you spin the globe around more than one full time in either direction and then draw a box and submit you'll get the error again...

We'll probably have to spend a bit more time for a full solution that translates what leaflet spits out into something the API can handle, but I could push this partial solution out to sciapps if you want?
