### ISSUE TITLE
Pick a Document REST API technology and implement first pass

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#13]
Spring rest docs or suitable alternative.  

AC: Docs should be publicly accessible.

**Comment by mcquinne** [comment]
Step one: investigate options.

- [ ] [Slate](https://github.com/lord/slate)
- [ ] [Swagger](http://swagger.io/)
- [ ] [Spring REST Docs](https://projects.spring.io/spring-restdocs/)

**Comment by dneufeldcu** [comment]
Swagger selected in first pass.  Consider spring-rest api docs integration.
