### ISSUE TITLE
Search relevancy - weightings

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#19]
Apply weights at query time

Using title, desc, keywords, DSMM, geometry, time, creator

**Comment by mcquinne** [comment]
AC:
Try several different weight combinations, then asses results.

**Comment by mcquinne** [comment]
Commit a8e6e8f7d159ad46c115aee9900134d8867539c4 addresses this issue...

ProTip: Don't begin your commit message directly with a reference to an issue like `#19 - ...`

**Comment by ajakz** [comment]
👍
