### ISSUE TITLE
Download granule option

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#20]
AC: Ability to click on a granule and download it.

**Comment by aaronjcaldwell** [comment]
Sprint review feedback:

- [ ] Hover over badges and get link preview

- [ ] Order badges consistently by type in both legend and record listing

**Comment by mcquinne** [comment]
I think this is done, unless we want to do another pass at which protocols we're detecting and how.

The currently list is:

| Indexed Protocol | Label |
|------------------|-------|
| download             | Download |
| ftp                        | FTP |
| noaa:las               | NOAA Live Access Server |
| opendap              | OPeNDAP |
| thredds                | THREDDS |
| http, https           | Web |

@cires-ncei/onestop  Anyone have strong opinions?

**Comment by ajakz** [comment]
Looks good!
