### ISSUE TITLE
Address travis false positive builds

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#23]
At least one travis build was [marked as passing when there were failing javascript tests](https://travis-ci.org/cires-ncei/onestop/builds/194884793#L487).

There's a [post on the travis blog](https://blog.travis-ci.com/2016-11-23-security-vulnerability-environment-variables/) from 2016/11/23 describing a security vulnerability that sounds vaguely similar to the error message in the build... but a) they say they contacted everyone who was effected and I haven't seen anything, and b) we've had builds with failing tests that were correctly marked as failed [as recently as last week](https://travis-ci.org/cires-ncei/onestop/builds/193523158).

It's not clear to me if this a real problem or not... Could be a travis bug? Maybe we need to regenerate our secrets? Maybe something is broken about our gradle build? Maybe we just need to clear the build cache and see if it happens again.

**Comment by dneufeldcu** [comment]
Needed to set flag in WebPack in order to stop the build.
