### ISSUE TITLE
Use <gmd:protocol> for links

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#26]
Instead of <gmd:name> for link labels we should be using <gmd:protocol> values.
See: https://github.com/cires-ncei/onestop/blob/master/api/src/main/groovy/ncei/onestop/api/service/MetadataParser.groovy#L352

This is the list of potential values: https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv

**Comment by dneufeldcu** [comment]
Change variable name to match xml tag : i.e. linkProtocol

**Comment by ajakz** [comment]
👍
