### ISSUE TITLE
Update header

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#27]
- [x] Clicking on NOAA logo should go to https://www.noaa.gov
- [x] Include About, Help links in Header (or menu)

**Comment by ajakz** [comment]
Since this overlaps with the direction we're going for #32, I'll cover these changes at the same time

**Comment by ajakz** [comment]
- [x] On landing page only, move search bar from header to main content area
- [ ] On landing page only, replicate NCEI header (links at top, with Search being OneStop)
- [ ] On landing page only, links shrink to burger menu at small screen width
- [ ] Elsewhere in OneStop app, links are always in burger menu at top right of header

**Comment by ajakz** [comment]
Going to postpone any burger menu work until after 1.0

**Comment by mcquinne** [comment]
Created #43 to put on the backlog to track that we want to use a burger menu to make Help and About accessible throughout the app. These header updates are good enough for now, though.
