### ISSUE TITLE
Clear search params on home button

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#29]
### Behavior:
Home button goes home and hides the params in the URL, but the search state is still set in redux and is applied if another search is run.

### Solution:
- [ ] Turn the home button/logo into a component with a container
- [ ] Dispatch a updateSearch action when the home button is clicked

### AC:
Going home clears your search params

**Comment by ajakz** [comment]
Removed the route change to collections view when empty search params are submitted, plus went ahead and cleared out old collection results ONLY on home button click so that the old results aren't still present on a new search. Otherwise.... looks good!
