### ISSUE TITLE
Trigger searches if needed on back/forward

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#30]
### Behavior:
There are cases where time traveling ought to fire a new search request but is not. e.g.:
1. Do a search --> results displayed
1. Click a facet --> new, narrower results displayed
1. Go back --> results not updated

### Options:
1. Detect when react-router-redux's `go`, `goForward`, `goBackward` actions are dispatched and throw additional actions of our own. NOTE: We do *NOT* want to do this in the router reducer.
1. Create actions of our own which wrap the react-router-redux actions.

### AC:
Time traveling should trigger data loading as necessary.

**Comment by ajakz** [comment]
👍
