### ISSUE TITLE
Implement text based section 508 landing page

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#31]
AC: Text based implementation e.g. NASA's Earth Data Search

**Comment by aaronjcaldwell** [comment]
https://www.hhs.gov/web/section-508/making-files-accessible/checklist/pdf/index.html

**Comment by aaronjcaldwell** [comment]
Useful chrome plugin: https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US
