### ISSUE TITLE
Landing page updates

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#34]
AC: 

- [x] Add [hero](https://github.com/18F/federalist-modern-team-template/blob/master/_layouts/home.html) text call out?  

- [x] Remove trending carousel

- [x] Improve topic search filters

- [x] Update/Add/Remove topic search icons

**Comment by ajakz** [comment]
Looks good to me. Closing until we (maybe) get feedback next week to change anything. 👍
