### ISSUE TITLE
Add about content

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#42]
Content: 
The OneStop Project is designed to improve NOAA's data discovery and access framework. Focusing on all layers of the framework and not just the user interface, OneStop is addressing data format and metadata best practices, ensuring more data are available through modern web services, working to improve the relevance of dataset searches, and advancing both collection-level metadata management and granule level metadata systems to accommodate the wide variety and vast scale of NOAA's data.

**Comment by mcquinne** [comment]
Looks good to me.
