### ISSUE TITLE
Add pagination to the client

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#46]
E.g. when you scroll to the bottom of the page there's a button to load more results.

AC:
- [x] pagination for collections
- [x] pagination for granules
- [x] reduce initial load size to 20

**Comment by ajakz** [comment]
[ ] Add collection pagination functionality
[ ] Fix all the broken tests
[ ] Make fanciest button ever
[ ] Add new tests/update existing for changed functionality

**Comment by mcquinne** [comment]
This has been reviewed by several folks and a related bug about it has already been fixed (#62), so this is done.
