### ISSUE TITLE
Index Data Stewardship Maturity Assessment (DSMA)

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#5]
DSMA may prove useful as a search relevancy criteria for collection level records and will eventually be incorporated into the UI.

A record with DSMA values is available here:
https://www.ngdc.noaa.gov/metadata/published/NOAA/NESDIS/NGDC/MGG/DEM/iso/xml/5230.xml

Values are text strings, up to 9 values are available at the following xpath:
/gmi:MI_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_ConceptualConsistency/gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record

Store codeList value for type information as well as the value e.g. intermediate

AC: The DSMA values are recorded in the ES index as numerics 0 is low 5 is high.

**Comment by ajakz** [comment]
- [ ] Update metadata parsing code to support DSMA scores
- [ ] Update metadata parser tests
- [ ] Update elasticsearch mappings
