### ISSUE TITLE
Improve client load time

### ISSUE THREAD

**Issue by mcquinne** [cires-ncei/onestop#52]
### Problem
The initial download to run the client is OUTRAGEOUS.

### Solutions
- [x] Consider upgrading to webpack 2.x in order to leverage ES6 tree shaking
- [x] Verify that our code and dependencies are not being included in both output bundles
- [x] Search for and remove unneeded dependencies
- [x] Create smaller bundles centered around different sections of the app and load them lazily

### Acceptance Criteria
The initial download is TOLERABLE.

**Comment by ajakz** [comment]
The initial download isn't just TOLERABLE, it's OUTRAGEOUSLY TOLERABLE.
