### ISSUE TITLE
Featured content

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#56]
AC: Separate js/config file for featured content. 5 featured content from OneStop ready data groups.

**Comment by mcquinne** [comment]
Initial featured data sets:
- GHRSST
- DEMs
- WOA 2013
- NWLON-PORTS
- CO-OPS

**Comment by ajakz** [comment]
Asked to make the list elements in the featured widget clickable

**Comment by aaronjcaldwell** [comment]
Revised a bit to prevent "permanent pause" on-hover. Also updated DEM sample image to smaller example for quicker load time. For both these and the collections results, if we don't end up indexing images in the future, we could potentially consider a technique similar to this: https://css-tricks.com/the-blur-up-technique-for-loading-background-images/

**Comment by mcquinne** [comment]
Done == closed
