### ISSUE TITLE
Create a standalone landing page

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#65]
AC: Should include text below; Use NESDIS look and feel (https://www.nesdis.noaa.gov/)

The NOAA Data Catalog is an inventory of all NOAA data collections. The user interface allows web-based searching by keywords and other attributes; machine-to-machine searching is available using the OGC CSW protocol (Open Geospatial Consortium Catalog Service for the Web).	NOAA OneStop provides enhanced collection and granule searching for selected datasets archived at the National Centers for Environmental Information (NCEI)

**Comment by bobalink** [comment]
Pushed repo to https://github.com/cires-ncei/data.noaa.gov-landing
