### ISSUE TITLE
Add configurable option to use ssl connection between webapps and ES

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#66]
AC: Code is configurable and works over SSL.

**Comment by mcquinne** [comment]
I think that ought to do it... but I haven't verified it. Need to figure out the best way to test this tomorrow.

**Comment by ajakz** [comment]
Leaving this reference link right here... https://www.elastic.co/guide/en/shield/current/ssl-tls.html

**Comment by ajakz** [comment]
Whoever is responsible for setting up the configuration of OneStop in production should be directed [here](https://github.com/cires-ncei/onestop/wiki/Application-Configuration-101) so we can see if the app works with SSL
