### ISSUE TITLE
Fix response type code - metadata endpoint

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#67]
If I post a file to it as a multipart request, and it is successfully added to OneStop, I will receive back a 207 response, and then the response body will contain one of the following:  if the file is being newly added to OneStop, it will include a 201 code and the json after will include "attributes":{"created":true}.  If the file is updating a previously existing record, it will again have a 207 code, but then the body will have a 200 (instead of a 201), and include "attributes":{"created":false).

However, this does not behave as I would expect when I send a single part request.  If I send a single part request and it is accepted, I get back a 201 whether the file is being newly added or is updating an existing record.  I can work around this because the attributes json is correctly displaying "created":true or "created":false as it should be.

I'm not sure whether it is correct to always send a 201 or to conditionally send either a 200 or 201 depending on the situation, but I figured you'd probably want the API to behave consistently in all situations.

**Comment by mcquinne** [comment]
Done == closed

**Comment by mcquinne** [comment]
Move to 1.0.0-RC2 since it's already done and will go out in that release candidate.
