### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#72]
- [x]  Confirm dates and bounding box fields work.

- [x] It would be very helpful if the information regarding the total number of matches found, and how many of them are displayed,  were contained in the first heading of the page. E.g., "Displaying results 1-20 of 900".

- [x] I saw no control for looking at the next 20 results.

**Comment by mcquinne** [comment]
All form fields are working correctly now, and there are error messages if invalid entries are made.

The "Home" and "About" links will be covered by #43

**Comment by mcquinne** [comment]
New task:

- [ ] The "508 Alternative Site" link should be easier to find with a screen reader on the home page

**Comment by mcquinne** [comment]
Pagination is installed and working for collections and granules. Also fixed a couple bugs and a11y issues along the way.

**Comment by mcquinne** [comment]
Checking off the new task I added; we'll move the link to the header, which will be covered by #43

**Comment by mcquinne** [comment]
I turned the "Search Results" and count line into a heading and verified that screen readers read it first after doing a search.

There is still an outstanding issue with screen readers and pagination, though: You can tab down and find the "Load More" button just fine, but when you click it the reader's focus stays on the button even though more results were inserted above it, so you have to tab backwards to read the things that were just loaded...
