### ISSUE TITLE
Headings for all the things

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#79]
-otherwise have to read whole page (cumbersome)

**Comment by ajakz** [comment]
- [ ] Use h1 for page title
- [ ] Use h2 for section titles
- [ ] Use h3 for proper elements within a section (like individual search results)
- [ ] Use descriptive HTML elements like section and nav where possible 
- [ ] Ordered list for search results?

**Comment by bobalink** [comment]
![image](https://cloud.githubusercontent.com/assets/1783526/24767413/1a241cd6-1abc-11e7-92ae-1ca5812ad94a.png)
