### ISSUE TITLE
Document the deployment process

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#80]
- [x] Process for CU server
- [x] Process for NCEI test server
- [x] Steps to tag a release & put in bintray

Where to store the documentation (format) ?
  google drive

**Comment by ajakz** [comment]
This is in our drive under One Stop > Documentation > Deployment Process.

I realized I haven't deployed to the NCEI test server yet, though. Dave do you have that documented somewhere?

**Comment by dneufeldcu** [comment]
Done
