### ISSUE TITLE
Include version info

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#89]
AC: Version info is displayed in footer.

**Comment by bobalink** [comment]
Basically done. we just need to decide as a team what we want to be displayed for version number. and then make the appropriate changes to the application.yml file and possibly the build.gradle.

**Comment by dneufeldcu** [comment]
Version not displayed.

**Comment by ajakz** [comment]
Hey @bobalink look into the nginx-onestop.conf file in ansible under the client role -- no proxy for the info endpoint

**Comment by ajakz** [comment]
🤘
