### ISSUE TITLE
Test new collections metadata records

### ISSUE THREAD

**Issue by dneufeldcu** [cires-ncei/onestop#90]
A new tarball representing geoportal collection metadata records is available.  Please load locally or into CU server to check results.

https://drive.google.com/open?id=0Bxy9G2TTQArMMkd3N2xpM1ZXS2c

**Comment by ajakz** [comment]
Loading locally, here's what I'm seeing:

The tarball contains 43,522 xml records. Of those, I'm seeing that 24,619 collections and 38,660 granules made it to the search index. Keep in mind that collections uploaded without granules will generate a fake granule record for the purposes of search (so every collection has at least 1 granule, which would be itself or true granules). These numbers don't imply that all records were ingested as collections, i.e., some had a populated parentIdentifier. These are the parentIdentifiers for which this is definitely the case based off a quick aggregation query: 
gov.noaa.ngdc:NOS_Hydrographic_Survey_Collection
gov.noaa.ngdc:ngdc_dems
gov.noaa.ngdc:Marine_Geology
EX1101
EX1102

Note that this excludes any that may have genuinely had 1 real granule...

Anyway, it looks like there is a consistent error in the failed records where the EX_GeographicBoundingBox has an empty string for one or more of the coordinates. 

Example snippet:

> 

      <gmd:extent>
        <gmd:EX_Extent id="boundingExtent">
          <gmd:geographicElement>
            <gmd:EX_GeographicBoundingBox id="boundingGeographicBoundingBox">
              <gmd:westBoundLongitude gco:nilReason="missing"/>
              <gmd:eastBoundLongitude gco:nilReason="missing"/>
              <gmd:southBoundLatitude gco:nilReason="missing"/>
              <gmd:northBoundLatitude gco:nilReason="missing"/>
            </gmd:EX_GeographicBoundingBox>
          </gmd:geographicElement>
          <gmd:temporalElement>
            <gmd:EX_TemporalExtent id="boundingTemporalExtent">
              <gmd:extent>
                <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
                  <gml:beginPosition>1987-06-01</gml:beginPosition>
                  <gml:endPosition>1987-07-24</gml:endPosition>
                </gml:TimePeriod>
              </gmd:extent>
            </gmd:EX_TemporalExtent>
          </gmd:temporalElement>
        </gmd:EX_Extent>
      </gmd:extent>
>

Mostly, if that is acceptable metadata, I think such an error implies that we need to accept a null bounding box for spatial extent. That feels gross but I'll keep my complaints to myself (or at least off the internet).

Also, just noticing again that with this data loaded, and a bunch of granules with overlapping spatial coordinates, we still have the big blue box on our granule view. I'll make an issue for our backlog to clean that up so we don't forget about it again.
