### ISSUE TITLE
Webpack 2 Round 2

### ISSUE THREAD

**Issue by aaronjcaldwell** [cires-ncei/onestop#94]
AC: 

- [x] Determine if ES6 abstractions are still leaking into final product

- [x] Ensure vendor code isn't being rebuilt for HMR (no slow reloads during dev)

- [x] Ensure IE 10+ compatibility (follow up on warning not seen in other browsers)

**Comment by aaronjcaldwell** [comment]
The babel-polyfill had to be loaded as the first element in the entry array for successful execution of several ES2015 abstractions such as 'Promise' or instance methods like 'Object.assign()'. The polyfill adds these methods to the global scope allowing them to be used throughout the application. Ideally, vendor libraries shouldn't require this polyfill in the global scope and instead should use their own polyfills locally. Upon moving to webpack 2, it appears there may have been a dependency load order race condition that was only exposed in IE where the polyfills had not yet been applied to the global scope causing functional errors which prevented the page from loading.

**Comment by aaronjcaldwell** [comment]
Several optimizations to improve build time on dev version:

- Remove unneeded uglify step from dev build

- Upgrade several packages related to build process, including webpack 2 itself which had a known bug creating longer load times in version 2.2.1 and others

- Picked more optimal source maps configuration which preserves files and line #s in debugging and allows for breakpoints

**Comment by ajakz** [comment]
Some notes, from testing sites on IE/Edge:
* On both master and this branch, the granule view is a mess for Edge (text disappears off screen; no scrolling available). It's obviously not a showstopper for this to be merged but we need to make an issue to address it. Weirdly, it's not an issue I'm seeing on IE versions.
* On IE10 (both branches), facet searching doesn't appear to work -- no new search happens. Again, not a reason not to merge this.
* Nothing worked on IE8, but then I noticed it was IE10+ compatibility we're going for...
* The new branch is noticeably less laggy on all browsers.
